version: 0.2

phases:
  pre_build:
    commands:
      - echo pre build
  build:
    commands:
      - echo Deployment started on `date`
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Update kubeconfig
      - aws eks update-kubeconfig --name gamecluster --region ap-southeast-2
      - kubectl config set-context --current --namespace=games      
      - kubectl get pods
      - kubectl create secret docker-registry regcred --docker-server=915922766016.dkr.ecr.ap-southeast-2.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password) --namespace=games
      - cd kubernetes
      - kubectl apply -f deployment.yaml
      - kubectl get pods
      - echo Deployment completed on `date`
  post_build:
    commands:
      - echo Post Deployment completed on `date`