version: 0.2

phases:
  pre_build:
    commands:
      - echo pre build
  build:
    commands:
      - echo Deployment started on `date`
      - echo Log into EKS
      - CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::915922766016:role/tf-eks-codepipeline_role --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - echo "Credentials Value is..  ${CREDENTIALS}"      
      - echo "AWS_ACCESS_KEY_ID...  ${AWS_ACCESS_KEY_ID}" 
      - aws sts get-caller-identity
      - echo Update KubeConfig      
      - aws eks update-kubeconfig --name gamecluster --region ap-southeast-2
      - kubectl config set-context --current --namespace=games      
      - kubectl get pods
      - kubectl create secret docker-registry regcred --docker-server=915922766016.dkr.ecr.ap-southeast-2.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password) --namespace=games
      - cd kubernetes
      - kubectl apply -f deployment.yaml
      - kubectl get pods
      - echo Deployment completed on `date`
  post_build:
    commands:
      - echo Post Deployment completed on `date`